// Generated by scripts/generate_observability.py from observability/slo.py.
// One scheduled query rule per objective. Edit the objectives, not this file.
//
// Severity maps to what happens, which is the only part of an alert that
// matters at four in the morning: sev1 wakes someone, sev3 makes a ticket.

@description('Application Insights component the rules query.')
param applicationInsightsId string

@description('Action group notified when a rule fires.')
param actionGroupId string

@description('Environment name, used in the rule names and the alert body.')
@allowed(['staging', 'production'])
param environmentName string

param location string = resourceGroup().location

// Success ratio: Five failures in a thousand. Above that, an agent mid-call with a customer starts seeing failures often enough to change how it behaves.
resource alert_success_ratio 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {
  name: 'telecom-mcp-${environmentName}-success-ratio'
  location: location
  properties: {
    description: 'Success ratio breached its objective. Successful and deduplicated calls over all calls. Deduplicated counts as success because the caller got the answer they asked for.'
    severity: 1
    enabled: true
    scopes: [ applicationInsightsId ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT30M'
    criteria: {
      allOf: [
        {
          query: '''
let calls = dependencies
    | where name == "execute_tool"
    | where timestamp > ago(30m)
    | extend outcome = tostring(customDimensions["outcome"]),
             tool = tostring(customDimensions["tool"]),
             stage = tostring(customDimensions["stage"]);
calls | summarize value = todouble(countif(outcome in ("ok"))) / todouble(max_of(count(), 1))
'''
          timeAggregation: 'Average'
          metricMeasureColumn: 'value'
          operator: 'LessThan'
          threshold: 0.995
          failingPeriods: {
            numberOfEvaluationPeriods: 2
            minFailingPeriodsToAlert: 2
          }
        }
      ]
    }
    autoMitigate: true
    actions: { actionGroups: [ actionGroupId ] }
  }
}

// Latency p95: A voice case has a five minute budget and an agent may need four tools inside it. Two seconds at p95 leaves room for the conversation.
resource alert_latency_p95_seconds 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {
  name: 'telecom-mcp-${environmentName}-latency-p95-seconds'
  location: location
  properties: {
    description: 'Latency p95 breached its objective. A voice case has a five minute budget and an agent may need several tools inside it. p95 is the number that decides whether that is possible.'
    severity: 1
    enabled: true
    scopes: [ applicationInsightsId ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT30M'
    criteria: {
      allOf: [
        {
          query: '''
let calls = dependencies
    | where name == "execute_tool"
    | where timestamp > ago(30m)
    | extend outcome = tostring(customDimensions["outcome"]),
             tool = tostring(customDimensions["tool"]),
             stage = tostring(customDimensions["stage"]);
calls | summarize value = percentile(duration, 95) / 1000.0
'''
          timeAggregation: 'Average'
          metricMeasureColumn: 'value'
          operator: 'GreaterThan'
          threshold: 2.0
          failingPeriods: {
            numberOfEvaluationPeriods: 2
            minFailingPeriodsToAlert: 2
          }
        }
      ]
    }
    autoMitigate: true
    actions: { actionGroups: [ actionGroupId ] }
  }
}

// Latency p99: Below the ten second tool timeout, so the tail is slow rather than refused. A ticket, not a page: one slow call does not lose the case.
resource alert_latency_p99_seconds 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {
  name: 'telecom-mcp-${environmentName}-latency-p99-seconds'
  location: location
  properties: {
    description: 'Latency p99 breached its objective. The customer who is already annoyed is in this bucket. Track it separately from p95: a p95 that holds while p99 doubles is a retry storm.'
    severity: 3
    enabled: true
    scopes: [ applicationInsightsId ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT30M'
    criteria: {
      allOf: [
        {
          query: '''
let calls = dependencies
    | where name == "execute_tool"
    | where timestamp > ago(30m)
    | extend outcome = tostring(customDimensions["outcome"]),
             tool = tostring(customDimensions["tool"]),
             stage = tostring(customDimensions["stage"]);
calls | summarize value = percentile(duration, 99) / 1000.0
'''
          timeAggregation: 'Average'
          metricMeasureColumn: 'value'
          operator: 'GreaterThan'
          threshold: 8.0
          failingPeriods: {
            numberOfEvaluationPeriods: 2
            minFailingPeriodsToAlert: 2
          }
        }
      ]
    }
    autoMitigate: true
    actions: { actionGroups: [ actionGroupId ] }
  }
}

// Calls over the time budget: Any call past the ten second budget is a customer sitting in silence. Rare enough to look at each one individually.
resource alert_calls_over_budget 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {
  name: 'telecom-mcp-${environmentName}-calls-over-budget'
  location: location
  properties: {
    description: 'Calls over the time budget breached its objective. Observations above the last histogram bucket. A quantile hides these; a count does not, and this is the one number that maps to a real customer sitting in silence.'
    severity: 3
    enabled: true
    scopes: [ applicationInsightsId ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT30M'
    criteria: {
      allOf: [
        {
          query: '''
let calls = dependencies
    | where name == "execute_tool"
    | where timestamp > ago(30m)
    | extend outcome = tostring(customDimensions["outcome"]),
             tool = tostring(customDimensions["tool"]),
             stage = tostring(customDimensions["stage"]);
calls | summarize value = countif(duration > 10000)
'''
          timeAggregation: 'Average'
          metricMeasureColumn: 'value'
          operator: 'GreaterThan'
          threshold: 0.0
          failingPeriods: {
            numberOfEvaluationPeriods: 2
            minFailingPeriodsToAlert: 2
          }
        }
      ]
    }
    autoMitigate: true
    actions: { actionGroups: [ actionGroupId ] }
  }
}

// Load shed ratio: Shedding is designed behaviour, so it is not a page. Sustained above one percent it is a capacity decision that someone has been avoiding.
resource alert_shed_ratio 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {
  name: 'telecom-mcp-${environmentName}-shed-ratio'
  location: location
  properties: {
    description: 'Load shed ratio breached its objective. Shedding is the designed behaviour under load, not a bug, but a non-zero value means capacity is the constraint and the next step is replicas.'
    severity: 3
    enabled: true
    scopes: [ applicationInsightsId ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT30M'
    criteria: {
      allOf: [
        {
          query: '''
let calls = dependencies
    | where name == "execute_tool"
    | where timestamp > ago(30m)
    | extend outcome = tostring(customDimensions["outcome"]),
             tool = tostring(customDimensions["tool"]),
             stage = tostring(customDimensions["stage"]);
calls | summarize value = todouble(countif(outcome == "shed")) / todouble(max_of(count(), 1))
'''
          timeAggregation: 'Average'
          metricMeasureColumn: 'value'
          operator: 'GreaterThan'
          threshold: 0.01
          failingPeriods: {
            numberOfEvaluationPeriods: 2
            minFailingPeriodsToAlert: 2
          }
        }
      ]
    }
    autoMitigate: true
    actions: { actionGroups: [ actionGroupId ] }
  }
}

// Backend retry ratio: Rises before failures do. Watching it is how the middleware's bad day is noticed before it becomes ours.
resource alert_backend_retry_ratio 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {
  name: 'telecom-mcp-${environmentName}-backend-retry-ratio'
  location: location
  properties: {
    description: 'Backend retry ratio breached its objective. Attempts beyond the first, over all attempts. Rises before failures do, which makes it the earliest honest warning we have.'
    severity: 3
    enabled: true
    scopes: [ applicationInsightsId ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT30M'
    criteria: {
      allOf: [
        {
          query: '''
let calls = dependencies
    | where name == "execute_tool"
    | where timestamp > ago(30m)
    | extend outcome = tostring(customDimensions["outcome"]),
             tool = tostring(customDimensions["tool"]),
             stage = tostring(customDimensions["stage"]);
calls | summarize value = todouble(countif(outcome == "failed")) / todouble(max_of(count(), 1))
'''
          timeAggregation: 'Average'
          metricMeasureColumn: 'value'
          operator: 'GreaterThan'
          threshold: 0.05
          failingPeriods: {
            numberOfEvaluationPeriods: 2
            minFailingPeriodsToAlert: 2
          }
        }
      ]
    }
    autoMitigate: true
    actions: { actionGroups: [ actionGroupId ] }
  }
}

// Output guardrail blocks: This should be zero forever. A single one means a write happened, the response was withheld, and redaction has met a field it does not know.
resource alert_output_guardrail_blocks 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {
  name: 'telecom-mcp-${environmentName}-output-guardrail-blocks'
  location: location
  properties: {
    description: 'Output guardrail blocks breached its objective. This should be zero forever. Any non-zero value means a write happened and the response was withheld, and it is a page rather than a ticket: redaction has met a field it does not know about.'
    severity: 1
    enabled: true
    scopes: [ applicationInsightsId ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT30M'
    criteria: {
      allOf: [
        {
          query: '''
let calls = dependencies
    | where name == "execute_tool"
    | where timestamp > ago(30m)
    | extend outcome = tostring(customDimensions["outcome"]),
             tool = tostring(customDimensions["tool"]),
             stage = tostring(customDimensions["stage"]);
calls | where stage startswith "output_" | summarize value = count()
'''
          timeAggregation: 'Average'
          metricMeasureColumn: 'value'
          operator: 'GreaterThan'
          threshold: 0.0
          failingPeriods: {
            numberOfEvaluationPeriods: 2
            minFailingPeriodsToAlert: 2
          }
        }
      ]
    }
    autoMitigate: true
    actions: { actionGroups: [ actionGroupId ] }
  }
}
